### ISSUE TITLE
minor typo in ttl description

### ISSUE THREAD

**Issue by ssj71** [harryhaaren/openAV-ArtyFX#14]
I was perusing your source and noticed this line:
doap:description "Side-chain Evenloper";
https://github.com/harryhaaren/openAV-ArtyFX/blob/master/artyfx.lv2/ducka.ttl#L37

I assume it should be "Enveloper"

cheers!

**Comment by harryhaaren** [comment]
This should have been closed by the commmit saying 'Fixed', manually closing now.
